### ISSUE TITLE
I can't mask urls

### ISSUE THREAD

**Issue by sadecemeliii** [LxaNce-Hacker/lxancephisher#1]
I'm trying to mask urls with cloudflared but it gives me url 2 and 3 blank

**Comment by sadecemeliii** [comment]
![resim_2024-05-12_023838454](https://github.com/LxaNce-Hacker/lxancephisher/assets/169564526/03094ae3-e0ac-4123-8145-91c0f42ab327)

**Comment by LxaNce-Hacker** [comment]
> I'm trying to mask urls with cloudflared but it gives me url 2 and 3 blank 
> 

Bro you need to install ```jq```

**Comment by sadecemeliii** [comment]
> > I'm trying to mask urls with cloudflared but it gives me url 2 and 3 blank
> 
> Bro you need to install `jq`

thanks

**Comment by LxaNce-Hacker** [comment]
> > > I'm trying to mask urls with cloudflared but it gives me url 2 and 3 blank
> > 
> > Bro you need to install `jq`
> 
> thanks

I'm always here to solve your issues 🙏 

You can join our community for getting latest updates 

https://chat.whatsapp.com/LVyCzdqc7264vSjWJhqJtm
